### ISSUE TITLE
Invalid style value

### ISSUE THREAD

**Issue by raacampbell** [raacampbell/notBoxPlot#5]
From FEX:

> Got an error using the new syntax (not legacy).
> notBoxPlot(rand(50,1),1,'style','sdline')
>  Error using notBoxPlot (line 211)
> The value of 'style' is invalid. Maximum variable size allowed by the function is exceeded.
> I'm using R2015a. Any solutions? 

 	

I'm not sure what's going on. I can't reproduce your problem in 2015b. I don't think I have a 2015a install to hand, but I'll look. The error is very strange: not only is it claiming that 'sdline' is invalid but that it's some how too large a variable. Do you see any other errors relating to input arguments?

**Comment by Huitzilipochtli** [comment]
I reproduce the same error using 2015a. Just downloaded the zip file from File Exchange. 

figure; clf
h=notBoxPlot(randn(10,1)+4,5,'style','line');
set(h.data,'color','m')  
h=notBoxPlot(randn(50,10));
set(h(5).data,'color','m')
Error using notBoxPlot (line 211)
The value of 'style' is invalid. Maximum variable size allowed by the function is
exceeded.

Update --- Works fine on 2016b.

**Comment by raacampbell** [comment]
Indeed, I also find that works on 2016b. The behavior of `strncmp` has changed at some point. I fixed the bug and tested it R2014a. The commit with the fix is: 2fbf98c8d6b75a91ccf27dc7eb8d13b393514425 You can just pull the new version or dowload the zip from the project home page. The FEX is updated nightly I think, so it lags behind.

**Comment by timostein** [comment]
Hi, I have a similar issue:

notBoxPlot(randn(20,5),[],'interval','tinterval')
Error using notBoxPlot (line 218)
The value of 'interval' is invalid. Maximum variable size allowed by the function is exceeded.

This is with R2015a as well.
Any help would be greatly appreciated!

**Comment by raacampbell** [comment]
Fixed: d096ab8b5e5504e5c8993e5030dcf24817e2dd45

**Comment by timostein** [comment]
Hi, had tried this as well, changing "Inf" to "4" but this did not fix the issue, now:

notBoxPlot(randn(20,5),[],'interval','tinterval')
Error using notBoxPlot (line 218)
The value of 'interval' is invalid. It must satisfy the function:
@(x)ischar(x)&&any(strncmp(x,{'SEM','tInterval'},4)).

**Comment by raacampbell** [comment]
Your error report suggests you're on a commit from before May 5th when I fixed the issue you report (see b6bf5b211a3f246123b616e3e82ab5d425aa74d4 and then again: d81db5d2f139e97662bd000087c6afad3016a29d). It looks like you have manually changed `inf` to `4` rather than pulling the latest version. Just pull and it should work: I tested the fix on R2014a.
